"""Stage 0 — Memory Preparation.

Produce a canonical `memory.json` (the pipeline's single source of truth for
insights) from either:
  - an existing playbook file (.txt / .json / .jsonl), OR
  - the repo's current trained playbook via `--from-file ...`.
Optionally append N dummy insights drawn from non-AppWorld domains so
Stage 4's bucketing has a known-noise baseline for threshold calibration.

Dummy insights are generated by the judge model (default gpt-4o-mini),
length-matched to the real insights' token-length distribution.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import sys
from datetime import datetime
from typing import Any

from .common import paths
from .common.config_hash import hash_config, hash_file, stage_cache_ok
from .common.io import append_jsonl, read_json, read_jsonl, read_text, write_json
from .common.litellm_client import JudgeClient, ensure_openai_env
from .common.playbook import parse_playbook_text, token_length_heuristic
from .common.progress import stage_context


STAGE_NAME = "stage0_memory"


DUMMY_SYSTEM_PROMPT = (
    "You are generating short advice-style insights that resemble entries in "
    "an engineering playbook, but about a NON-software domain. The insights "
    "must read as confident, specific, actionable rules from the target "
    "domain. Do NOT reference programming, APIs, apps, code, accounts, or "
    "software workflows."
)


DUMMY_USER_TEMPLATE = (
    "Write exactly ONE insight about the domain '{domain}'.\n"
    "It must be approximately {target_tokens} tokens long (about {target_chars} characters). "
    "Write in the same terse, imperative style as an engineering playbook: "
    "start with the action or principle, then one clause of justification. "
    "Do NOT add numbering, bullet points, brackets, quotes, or prefixes. "
    "Do NOT mention software, APIs, tokens, apps, or code. "
    "Just output the insight text itself on a single line.\n\n"
    "Examples (format reference, different domains):\n"
    "- In baking, always weigh flour with a scale rather than measuring by volume. "
    "Volume measurements vary by packing density and humidity, which cascades into dough hydration errors.\n"
    "- When coaching a basketball team, always establish defensive assignments before tipoff. "
    "Clear matchups prevent switching confusion during fast transitions.\n"
    "- For household budgeting, record every expense within 24 hours of occurrence. "
    "Delayed entries are routinely misremembered, especially small recurring ones.\n\n"
    "Now generate one insight about '{domain}':"
)


DEFAULT_DUMMY_DOMAINS = [
    "cooking",
    "sports_coaching",
    "personal_finance",
    "general_health",
    "home_gardening",
    "music_practice",
]


def _load_source(path: str) -> list[dict[str, Any]]:
    """Load insights from a source file — .txt playbook, .json, or .jsonl."""
    ext = os.path.splitext(path)[1].lower()
    if ext == ".txt":
        text = read_text(path)
        return parse_playbook_text(text)
    if ext == ".json":
        obj = read_json(path)
        if isinstance(obj, dict) and "insights" in obj:
            return list(obj["insights"])
        if isinstance(obj, list):
            return list(obj)
        raise ValueError(f"Unexpected JSON shape in {path}")
    if ext == ".jsonl":
        return list(read_jsonl(path))
    # Fallback: try txt parser
    text = read_text(path)
    return parse_playbook_text(text)


def _normalize_insights(
    raw: list[dict[str, Any]],
    default_source: str = "provided",
) -> list[dict[str, Any]]:
    """Ensure every insight has id, text, source, domain, section, token_length."""
    normalized: list[dict[str, Any]] = []
    for i, ins in enumerate(raw):
        if "text" not in ins:
            raise ValueError(f"Insight at index {i} has no 'text' field: {ins}")
        ins_id = ins.get("id") or f"provided-{i+1:05d}"
        text = str(ins["text"]).strip()
        entry: dict[str, Any] = {
            "id": ins_id,
            "text": text,
            "source": ins.get("source") or default_source,
            "domain": ins.get("domain") or "appworld",
            "section": ins.get("section") or "OTHERS",
            "token_length": int(ins.get("token_length") or token_length_heuristic(text)),
            "metadata": ins.get("metadata") or {},
        }
        normalized.append(entry)
    return normalized


def _token_distribution(insights: list[dict[str, Any]]) -> dict[str, Any]:
    if not insights:
        return {"mean": 40, "p25": 30, "p50": 40, "p75": 60, "min": 20, "max": 80, "n": 0}
    tokens = sorted(int(i["token_length"]) for i in insights)
    n = len(tokens)
    def q(p):
        return tokens[min(n - 1, int(p * (n - 1)))]
    return {
        "mean": sum(tokens) / n,
        "p25": q(0.25),
        "p50": q(0.50),
        "p75": q(0.75),
        "min": tokens[0],
        "max": tokens[-1],
        "n": n,
    }


def _sample_target_tokens(rng: random.Random, dist: dict[str, Any]) -> int:
    lo = max(15, int(dist["p25"]))
    hi = max(lo + 1, int(dist["p75"]))
    return rng.randint(lo, hi)


def _generate_dummies(
    n: int,
    domains: list[str],
    dist: dict[str, Any],
    judge: JudgeClient,
    log_path: str,
    rng: random.Random,
) -> list[dict[str, Any]]:
    """Generate `n` dummy insights, each from a domain in `domains`.

    Writes the prompt + raw completion to `log_path` so the user can audit
    exactly what was generated.
    """
    out: list[dict[str, Any]] = []
    idx = 0
    attempts = 0
    max_attempts = n * 3
    while len(out) < n and attempts < max_attempts:
        attempts += 1
        domain = domains[idx % len(domains)]
        idx += 1
        target_tokens = _sample_target_tokens(rng, dist)
        prompt = DUMMY_USER_TEMPLATE.format(
            domain=domain,
            target_tokens=target_tokens,
            target_chars=target_tokens * 4,
        )
        try:
            content, cost = judge.generate(prompt, system=DUMMY_SYSTEM_PROMPT)
        except Exception as exc:
            append_jsonl(log_path, {
                "ts": datetime.utcnow().isoformat() + "Z",
                "attempt": attempts,
                "domain": domain,
                "target_tokens": target_tokens,
                "error": str(exc),
            })
            continue
        text = content.strip().strip("\"'")
        if text.startswith("-"):
            text = text.lstrip("-").strip()
        # Single line, non-empty, not absurdly off length
        ok = bool(text) and "\n" not in text
        actual_tokens = token_length_heuristic(text) if ok else 0
        # Generous length band: 0.25x to 3x of target
        if ok and (actual_tokens < max(8, target_tokens // 4) or actual_tokens > target_tokens * 3):
            ok = False
        append_jsonl(log_path, {
            "ts": datetime.utcnow().isoformat() + "Z",
            "attempt": attempts,
            "domain": domain,
            "target_tokens": target_tokens,
            "actual_tokens": actual_tokens,
            "ok": ok,
            "prompt": prompt,
            "response": content,
            "cost_usd": cost,
        })
        if not ok:
            continue
        dummy_id = f"dummy-{len(out)+1:05d}"
        out.append({
            "id": dummy_id,
            "text": text,
            "source": "dummy",
            "domain": domain,
            "section": "DUMMY_INSIGHTS",
            "token_length": actual_tokens,
            "metadata": {"target_tokens": target_tokens, "attempts": attempts},
        })
    return out


def run(
    from_file: str,
    out_path: str,
    append_dummies: int = 0,
    dummy_domains: list[str] | None = None,
    judge_model: str = "gpt-4o-mini",
    judge_provider: str = "openai",
    force: bool = False,
    seed: int = 100,
) -> str:
    """Programmatic entrypoint. Returns the output path."""
    domains = dummy_domains or DEFAULT_DUMMY_DOMAINS
    cfg = {
        "from_file": os.path.abspath(from_file),
        "append_dummies": append_dummies,
        "dummy_domains": domains,
        "judge_model": judge_model,
        "judge_provider": judge_provider,
        "seed": seed,
    }
    cfg_hash = hash_config(cfg, input_file_paths=[from_file] if os.path.exists(from_file) else [])
    if not force and stage_cache_ok(out_path, cfg_hash):
        print(f"[{STAGE_NAME}] cache hit — output already up to date: {out_path}")
        return out_path
    run_dir = os.path.dirname(os.path.abspath(out_path))
    with stage_context(STAGE_NAME, run_dir):
        raw = _load_source(from_file)
        insights = _normalize_insights(raw, default_source="provided")
        print(f"[{STAGE_NAME}] loaded {len(insights)} source insights from {from_file}")
        dist = _token_distribution(insights)
        print(f"[{STAGE_NAME}] token-length distribution: {dist}")
        rng = random.Random(seed)
        if append_dummies > 0:
            ensure_openai_env(provider=judge_provider)
            log_path = os.path.join(run_dir, "dummy_generation_log.jsonl")
            # Clear log so it reflects just this run.
            if os.path.exists(log_path):
                os.remove(log_path)
            judge = JudgeClient(model=judge_model, provider=judge_provider, use_cache=True)
            print(f"[{STAGE_NAME}] generating {append_dummies} dummies via {judge_model}...")
            dummies = _generate_dummies(append_dummies, domains, dist, judge, log_path, rng)
            if len(dummies) < append_dummies:
                print(f"[{STAGE_NAME}] WARNING: only generated {len(dummies)}/{append_dummies} dummies (see {log_path})")
            insights = insights + dummies
        # Re-id "provided-*" if source didn't come with IDs (rare path; txt-source has IDs)
        for i, ins in enumerate(insights):
            if not ins.get("id"):
                ins["id"] = f"provided-{i+1:05d}"
        n_dummies = sum(1 for ins in insights if ins.get("source") == "dummy")
        n_real = len(insights) - n_dummies
        blob = {
            "insights": insights,
            "config": cfg,
            "config_hash": cfg_hash,
            "created_at": datetime.utcnow().isoformat() + "Z",
            "stats": {
                "n_total": len(insights),
                "n_real": n_real,
                "n_dummies": n_dummies,
                "token_distribution_real": dist,
            },
        }
        write_json(out_path, blob)
        print(f"[{STAGE_NAME}] wrote memory.json: {out_path}  (n_total={len(insights)}, dummies={n_dummies})")
    return out_path


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Stage 0: Memory preparation")
    p.add_argument("--from-file", required=True, help="Source playbook/memory (.txt/.json/.jsonl)")
    p.add_argument("--out", required=True, help="Output memory.json path")
    p.add_argument("--append-dummies", type=int, default=0, help="Number of dummy insights to generate")
    p.add_argument("--dummy-domains", default=",".join(DEFAULT_DUMMY_DOMAINS),
                   help="Comma-separated list of non-AppWorld domains for dummies")
    p.add_argument("--judge-model", default="gpt-4o-mini")
    p.add_argument("--judge-provider", default="openai")
    p.add_argument("--seed", type=int, default=100)
    p.add_argument("--force", action="store_true", help="Ignore cache and regenerate")
    args = p.parse_args(argv)
    domains = [d.strip() for d in args.dummy_domains.split(",") if d.strip()]
    run(
        from_file=args.from_file,
        out_path=args.out,
        append_dummies=args.append_dummies,
        dummy_domains=domains,
        judge_model=args.judge_model,
        judge_provider=args.judge_provider,
        force=args.force,
        seed=args.seed,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
